server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo1
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
logging:
  level:
    com.leyou: debug